services:

  node1:
    build: ./node
    container_name: node1
    hostname: node1
    networks:
      - ops-net

  node2:
    build: ./node
    container_name: node2
    hostname: node2
    networks:
      - ops-net

  node3:
    build: ./node
    container_name: node3
    hostname: node3
    networks:
      - ops-net

  controller:
    build: ./controller
    container_name: controller
    networks:
      - ops-net
    ports:
      - "5000:5000"
    depends_on:
      - node1
      - node2
      - node3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - ops-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - ops-net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

networks:
  ops-net:
    driver: bridge
